const { readFileSync } = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const code = readFileSync('dist/app.js', 'utf8');
const context = vm.createContext({});
vm.runInContext(code.slice(0, code.indexOf('const state =')), context);
const items = vm.runInContext('opportunities', context);
const supportedTypes = vm.runInContext('typeOrder', context);
assert.equal(items.length, 87);
for (const item of items) {
  assert.ok(supportedTypes.includes(item.type), `${item.id}: unsupported filter type ${item.type}`);
  for (const key of ['description', 'location', 'duration', 'paid', 'deadline', 'eligibilityDetails', 'application', 'url']) {
    assert.ok(item[key] && item[key].length > 0, `${item.id}: missing ${key}`);
  }
  assert.equal(new URL(item.url).protocol, 'https:');
  assert.notEqual(item.deadline, 'Applications open');
  assert.ok(['open', 'rolling', 'on-demand'].includes(item.status));
  if (item.mapped !== false && item.region !== 'Online' && item.country !== 'Global') {
    assert.ok(Number.isFinite(item.lat) && Number.isFinite(item.lon));
  }
}
assert.match(code, /if \(!event.target.closest\("a, button, summary, input"\)\) select\(\)/);
assert.match(code, /if \(event.target !== card\) return/);
assert.match(code, /class="opportunity-facts"/);
assert.match(code, /rel="noopener noreferrer"/);
assert.equal(items.some(item => item.id === 'maxim-internship'), false);
assert.equal(items.some(item => item.id === 'heritage-high-school-fellowship-2027'), false);
for (const id of ['fire-campus-2026', 'mercatus-complex-2027', 'tfas-santiago-2027', 'hoover-student-2026', 'aei-2601', 'aei-2602', 'aei-2607', 'aei-2627', 'tfas-asia', 'hudson-summer-fellowship-2027']) {
  assert.equal(items.some(item => item.id === id), false, id);
}
const hudson = items.find(item => item.id === 'hudson-policy-oct2026');
assert.equal(/fully funded/i.test(`${hudson.paid} ${hudson.fundingDetails}`), false);
assert.match(`${hudson.paid} ${hudson.fundingDetails}`, /free of charge/i);
assert.match(items.find(item => item.id === 'reason-journalism').deadline, /deadline year inferred; confirm on the official page/);
assert.match(items.find(item => item.id === 'tfas-dc-academic-internship-summer-2027').deadline, /deadline year inferred; confirm on the official page/);
assert.equal(items.find(item => item.id === 'hillsdale-online').region, 'Online');
assert.equal(items.find(item => item.id === 'plf-research-spring-2027').region, 'Online');
assert.equal(new Set(items.map(item => item.id)).size, items.length);
const byId = id => items.find(item => item.id === id);
const bpc = byId('bpc-spring-2027-internships');
assert.match(`${bpc.paid} ${bpc.fundingDetails} ${bpc.description}`, /part-time/i);
assert.match(`${bpc.paid} ${bpc.fundingDetails}`, /3,000/);
assert.equal(/6,?000/.test(`${bpc.paid} ${bpc.fundingDetails} ${bpc.description} ${bpc.deadline}`), false);
const fai = byId('fai-conservative-ai-policy-fellowship');
assert.match(fai.deadline, /30 October 2026/);
assert.match(`${fai.description} ${fai.eligibilityDetails}`, /conservative policy professionals/i);
assert.match(fai.eligibilityDetails, /not a general student programme/i);
const volcker = byId('volcker-nextgen-summer-policy-academy-2027');
assert.match(volcker.deadline, /15 December 2026, 11:59 pm PT \(Pacific\)/);
assert.equal(volcker.mapped, false);
const ppia = byId('ppia-junior-summer-institute-2027');
assert.match(ppia.deadline, /6 November 2026, 11:59 pm EST \(Eastern\)/);
assert.equal(ppia.mapped, false);
assert.match(byId('ij-semester-clerkship-spring-2027').eligibilityDetails, /law students/i);
assert.match(byId('ij-fall-2026-legal-intensive').eligibilityDetails, /law students/i);
assert.match(byId('ij-development-internship').description, /not a policy placement/i);
assert.match(byId('acton-spring-2027-semester-internship').deadline, /30 November 2026/);
assert.match(byId('atlas-network-spring-2027-internships').deadline, /31 December 2026/);
assert.equal(byId('yal-law-clerk-spring-2027').region, 'Online');
assert.equal(byId('ij-semester-clerkship-spring-2027').mapped, false);
for (const id of [
  'atlantic-council-ygp-spring-2027', 'bpc-summer-2027-internships', 'acton-emerging-leaders-program-2027',
  'ij-dave-kennedy-fellowship', 'ij-hellman-undergraduate-fellowship', 'roosevelt-network-forge',
  'roosevelt-network-roosevelt-in-washington', 'roosevelt-network-emerging', 'ashbrook-academy',
  'ifg-research-internship-2027-28', 'cbpp-spring-2027-internships', 'ppi-policy-fellow',
  'ppi-communications-government-relations-fellow', 'wilson-center-research-fellowship',
  'niskanen-internship-program', 'takshashila-nas-fellowship-2026-27', 'ile-puerto-rico-academia-libertad-liderazgo',
  'iseas-wang-gungwu-visiting-fellows'
]) {
  assert.equal(items.some(item => item.id === id), false, id);
}
assert.match(code, /Source reviewed 11 Sep 2026/);
const manning = byId('manning-foundation-student-essay-contest-2026');
assert.equal(manning.type, 'Essay competition');
assert.equal(manning.region, 'Online');
assert.match(manning.deadline, /Midnight, Sunday 8 November 2026 \(time zone not stated\)/);
assert.match(`${manning.description} ${manning.eligibilityDetails}`, /Canadian undergraduates/i);
assert.match(`${manning.description} ${manning.eligibilityDetails}`, /not an internship/i);
assert.match(`${manning.paid} ${manning.fundingDetails}`, /\$7,000 in prizes/);
assert.equal(manning.url, 'https://manningfoundation.org/4th-annual-morgan-trottier-student-essay-contest/');
const piensa = byId('fundacion-piensa-jovenes-lideres-2026');
assert.match(`${piensa.description} ${piensa.fundingDetails}`, /recognition award/i);
assert.match(`${piensa.description} ${piensa.fundingDetails} ${piensa.paid}`, /no prize money|no money awarded/i);
assert.match(`${piensa.description} ${piensa.eligibilityDetails}`, /18-35/);
assert.match(`${piensa.description} ${piensa.eligibilityDetails}`, /Valpara[ií]so/);
assert.match(`${piensa.description} ${piensa.eligibilityDetails}`, /Spanish/);
assert.match(piensa.deadline, /23:59, Friday 30 October 2026 \(Chile time implied; time zone not stated\)/);
assert.equal(piensa.url, 'https://jovenesliderespiensa.cl/');
assert.match(piensa.application, /https:\/\/docs\.google\.com\/forms\/d\/e\/1FAIpQLSediVYK3-CZngcu0QNnN3BTAFcvySatmS6EP0nFvGiDPGCG3w\/viewform/);
const ifese = byId('ifese-studentenpresentaties-2027');
assert.equal(ifese.deadline, 'Closing date unclear on the official page, apply early.');
assert.equal(/1 May 2027|May 2027|mei 2027|donderdag/i.test(JSON.stringify(ifese)), false);
assert.match(`${ifese.description} ${ifese.eligibilityDetails}`, /Dutch-language/);
assert.match(`${ifese.description} ${ifese.eligibilityDetails}`, /[Bb]achelor/);
assert.match(`${ifese.description} ${ifese.eligibilityDetails}`, /five places/);
assert.match(`${ifese.description} ${ifese.eligibilityDetails}`, /first come, first served/);
assert.match(ifese.application, /jens\.vanmieghem@ifese\.be/);
assert.equal(ifese.mapped, false);
assert.equal(ifese.url, 'https://www.ifese.be/studenten/studentenpresentaties/');
const hayek = byId('hayek-gesellschaft-juniorenkreis-wissenschaft-potsdam-2026');
assert.equal(hayek.type, 'Seminar');
assert.match(`${hayek.program} ${hayek.description}`, /academic weekend/i);
assert.match(`${hayek.description} ${hayek.eligibilityDetails}`, /not an internship/i);
assert.match(`${hayek.description} ${hayek.duration} ${hayek.deadline}`, /Friday 6 to Sunday 8 November 2026/);
assert.match(`${hayek.eligibilityDetails} ${hayek.description}`, /18-35/);
assert.match(`${hayek.eligibilityDetails} ${hayek.description}`, /German/);
assert.match(`${hayek.deadline} ${hayek.application}`, /[Nn]o fixed deadline/);
assert.match(hayek.application, /KF_Israel\[at\]gmx\.de/);
assert.equal(hayek.url, 'https://hayek.de/veranstaltungen/juniorenkreis-wissenschaft-kapital-produktion-und-kapitalismus/');
const insm = byId('iw-koeln-insm-studentischer-mitarbeiter-volkswirtschaft');
const koeln = byId('iw-koeln-student-finanz-immobilienmaerkte');
for (const job of [insm, koeln]) {
  assert.match(`${job.program} ${job.description} ${job.eligibilityDetails}`, /[Ss]tudent job \(Werkstudent/);
  assert.match(`${job.description} ${job.eligibilityDetails}`, /not an internship/i);
  assert.match(`${job.description} ${job.eligibilityDetails}`, /German/);
  assert.match(job.deadline, /Rolling until filled/);
}
assert.match(koeln.deadline, /Starts 1 October 2026 and may already be filled/);
assert.equal(/already be filled/.test(insm.deadline), false);
assert.equal(insm.url, 'https://k60828.coveto.de/job-studentischer-mitarbeiter-volkswirtschaft-wirtschaftspolitik-m-w-d-berlin-1173.html');
assert.equal(koeln.url, 'https://k60828.coveto.de/job-studentischer-mitarbeiter-m-w-d-mit-dem-schwerpunkt-finanz-und-immobilienmaerkte-koeln-1174.html');
const iness = byId('iness-ekonomicky-base-camp-2026');
assert.equal(iness.type, 'Seminar');
assert.equal(iness.region, 'Europe');
assert.match(iness.deadline, /Monday 5 October 2026/);
assert.match(iness.deadline, /no time or time zone stated/);
assert.match(`${iness.description} ${iness.deadline}`, /few days away|Closes in a few days/);
assert.match(`${iness.description} ${iness.paid} ${iness.fundingDetails}`, /FEE-BASED/);
assert.match(`${iness.description} ${iness.paid} ${iness.fundingDetails}`, /EUR 159/);
assert.match(`${iness.description} ${iness.paid} ${iness.fundingDetails}`, /EUR 299/);
assert.match(`${iness.description} ${iness.paid} ${iness.fundingDetails}`, /EUR 109/);
assert.match(`${iness.description} ${iness.fundingDetails}`, /scholarship/);
assert.match(`${iness.description} ${iness.eligibilityDetails}`, /Slovak-language/);
assert.match(`${iness.description} ${iness.eligibilityDetails}`, /[Ss]tudents are prioritised/);
assert.match(`${iness.description} ${iness.location}`, /Martin/);
assert.match(iness.application, /iness@iness\.sk/);
assert.match(iness.application, /https:\/\/docs\.google\.com\/forms\/d\/e\/1FAIpQLScJGDp8ak8PZd3MjZFUTg51H8KSKSnLxRj3QzoM1P8rodomRg\/viewform/);
assert.equal(iness.url, 'https://ekonomickybasecamp.sk/prihlasovanie/');
const praktik = byId('centrum-for-rattvisa-praktik-var-2027');
assert.equal(praktik.type, 'Internship');
assert.equal(praktik.region, 'Europe');
assert.equal(praktik.paid, 'No');
assert.match(`${praktik.description} ${praktik.eligibilityDetails} ${praktik.fundingDetails}`, /[Uu]npaid/);
assert.match(`${praktik.description} ${praktik.eligibilityDetails}`, /[Ll]aw students/);
assert.match(`${praktik.description} ${praktik.eligibilityDetails}`, /[Pp]robably Swedish-language/);
assert.match(`${praktik.description} ${praktik.duration}`, /10 weeks/);
assert.match(`${praktik.description} ${praktik.deadline} ${praktik.application}`, /[Rr]olling/);
assert.match(praktik.deadline, /Sunday 11 October 2026/);
assert.match(praktik.deadline, /no time or time zone stated/);
assert.match(praktik.application, /rekrytering@centrumforrattvisa\.se/);
assert.equal(praktik.url, 'https://centrumforrattvisa.se/student/praktik/');
const fil = byId('fil-vi-premio-periodismo-joven-carlos-alberto-montaner');
assert.equal(fil.type, 'Essay competition');
assert.equal(fil.region, 'Online');
assert.match(`${fil.program} ${fil.description} ${fil.paid}`, /PRIZE/);
assert.match(`${fil.description} ${fil.eligibilityDetails}`, /journalists under 35/);
assert.match(`${fil.description} ${fil.eligibilityDetails}`, /any nationality/);
assert.match(`${fil.description} ${fil.eligibilityDetails}`, /Spanish-language/);
assert.match(`${fil.description} ${fil.eligibilityDetails} ${fil.fundingDetails}`, /not a student programme or internship/);
assert.match(`${fil.paid} ${fil.fundingDetails}`, /USD 10,000/);
assert.match(fil.deadline, /Sunday 25 October 2026/);
assert.match(fil.deadline, /no time or time zone stated/);
assert.equal(fil.url, 'https://catedravargasllosa.org/inicio/index.php/premio-periodismo-joven/');
const shaftesbury = byId('first-liberty-crcd-shaftesbury-fellowship-2027');
assert.equal(shaftesbury.type, 'Fellowship');
assert.equal(shaftesbury.region, 'United States');
assert.equal(shaftesbury.eligibility, 'Some restrictions');
assert.equal(shaftesbury.paid, 'Stipend plus housing');
assert.match(shaftesbury.paid, /stipend/i);
assert.match(`${shaftesbury.paid} ${shaftesbury.fundingDetails}`, /housing/i);
assert.match(`${shaftesbury.description} ${shaftesbury.eligibilityDetails}`, /upper-level undergraduates and recent graduates/i);
assert.match(`${shaftesbury.description} ${shaftesbury.eligibilityDetails}`, /liberty-related field/i);
assert.match(`${shaftesbury.description} ${shaftesbury.eligibilityDetails}`, /Christian-oriented religion, culture and democracy/i);
assert.match(`${shaftesbury.description} ${shaftesbury.location} ${shaftesbury.duration}`, /Plano, Texas/);
assert.match(`${shaftesbury.description} ${shaftesbury.duration}`, /24 May to 30 July 2027/);
assert.match(`${shaftesbury.description} ${shaftesbury.duration}`, /about 10 weeks/i);
assert.match(`${shaftesbury.description} ${shaftesbury.fundingDetails}`, /weekly stipend/i);
assert.match(`${shaftesbury.description} ${shaftesbury.fundingDetails}`, /non-US citizens may be ineligible for the stipend/i);
assert.match(`${shaftesbury.deadline} ${shaftesbury.description} ${shaftesbury.application}`, /Monday 15 February 2027/);
assert.match(`${shaftesbury.deadline} ${shaftesbury.application}`, /no time or time zone stated/);
assert.match(`${shaftesbury.deadline} ${shaftesbury.description} ${shaftesbury.application}`, /[Rr]olling/);
assert.match(shaftesbury.application, /Paycor portal \(not checked by us\)/);
assert.match(shaftesbury.application, /jbarr@firstliberty\.org/);
assert.equal(shaftesbury.url, 'https://crcd.net/programs/shaftesbury-fellowship/');
assert.equal(shaftesbury.source, 'Official source reviewed 11 Sep 2026');
const johnjay = byId('john-jay-fellows-spring-2027');
assert.equal(johnjay.type, 'Fellowship');
assert.equal(johnjay.region, 'United States');
assert.equal(johnjay.eligibility, 'Some restrictions');
assert.match(johnjay.paid, /stipend/i);
assert.match(johnjay.paid, /free/i);
assert.notEqual(johnjay.paid, 'No');
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /explicitly Christian programme/);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /demonstrated Christian commitment/i);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /daily group prayer/);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /live-in Christian community/);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /recent college graduates and young professionals/i);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /not current students/i);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /completed college/i);
assert.match(`${johnjay.description} ${johnjay.eligibilityDetails}`, /GPA 3\.0\+/);
assert.match(`${johnjay.description} ${johnjay.location} ${johnjay.duration}`, /Langhorne, Pennsylvania/);
assert.match(`${johnjay.description} ${johnjay.location}`, /live-in residency/i);
assert.match(`${johnjay.description} ${johnjay.duration}`, /Friday 8 January to Saturday 24 April 2027/);
assert.match(`${johnjay.description} ${johnjay.duration}`, /about four months/i);
assert.match(`${johnjay.description} ${johnjay.paid} ${johnjay.fundingDetails}`, /\$875 monthly stipend/);
assert.match(`${johnjay.description} ${johnjay.fundingDetails}`, /[Tt]uition free/);
assert.match(`${johnjay.description} ${johnjay.fundingDetails}`, /free housing/);
assert.match(`${johnjay.description} ${johnjay.fundingDetails}`, /externship afterwards is unpaid unless the host pays/);
assert.match(`${johnjay.deadline} ${johnjay.application}`, /Sunday 1 November 2026/);
assert.match(`${johnjay.deadline} ${johnjay.application}`, /no time or time zone stated/);
assert.match(johnjay.application, /not opened by us/);
assert.match(johnjay.application, /admin@johnjayinstitute\.org/);
assert.equal(johnjay.url, 'https://www.johnjayfellows.com/academic-calendar');
assert.equal(johnjay.source, 'Official source reviewed 11 Sep 2026');
const ocpa = byId('ocpa-fears-fellowship-okc-2027');
assert.equal(ocpa.type, 'Seminar');
assert.equal(ocpa.region, 'United States');
assert.equal(ocpa.eligibility, 'Some restrictions');
assert.equal(ocpa.paid, 'Not stated');
assert.equal(/Paid|stipend|Scholarship|Prize|Free/i.test(ocpa.paid), false);
assert.match(`${ocpa.description} ${ocpa.eligibilityDetails}`, /young leaders aged 18 to 35/i);
assert.match(`${ocpa.description} ${ocpa.eligibilityDetails}`, /professionals and students/i);
assert.match(`${ocpa.program} ${ocpa.description} ${ocpa.eligibilityDetails}`, /reading and lecture seminar/i);
assert.match(`${ocpa.description} ${ocpa.location} ${ocpa.duration}`, /Oklahoma City/);
assert.match(`${ocpa.description} ${ocpa.duration}`, /in-person Saturday sessions/i);
assert.match(`${ocpa.description} ${ocpa.duration}`, /9:30 am to 1:00 pm/);
assert.match(`${ocpa.description} ${ocpa.duration}`, /23 January, 6 February, 20 February, 6 March and 20 March 2027/);
assert.match(`${ocpa.description} ${ocpa.eligibilityDetails}`, /[Ll]imited places/);
assert.match(`${ocpa.description} ${ocpa.application}`, /request form only/i);
assert.match(`${ocpa.description} ${ocpa.paid} ${ocpa.fundingDetails}`, /[Nn]ot stated/);
assert.match(`${ocpa.description} ${ocpa.fundingDetails}`, /no fee mentioned on the pages we read/);
assert.match(`${ocpa.deadline} ${ocpa.application}`, /Friday 18 December 2026/);
assert.match(`${ocpa.deadline} ${ocpa.application}`, /no time or time zone stated/);
assert.match(ocpa.application, /Matt@OCPAthink\.org/);
assert.equal(ocpa.url, 'https://www.fearsfellowship.com/a-3-lightbox.html');
assert.equal(ocpa.source, 'Official source reviewed 11 Sep 2026');
assert.equal(/2023|Copyright|planned for OKC and Tulsa/i.test(JSON.stringify(ocpa)), false);
console.log('PASS: 87 reviewed records, official HTTPS sources, status fields and independent link controls.');
